# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RIM0pyWlXtXmemeT50Kc4p5RrKlMy1t5
"""

import streamlit as st
import pandas as pd

st.title("Imperative of λύω")

# = CSS styling with tooltip support =
st.markdown("""
    <style>
        .block-container {
            max-width: unset;
            padding-left: 15rem;
            padding-right: 15rem;
            padding-top: 2rem;
            padding-bottom: 1rem;
            overflow-x: auto;
        }

        /* Responsive adjustments for mobile */
        @media (max-width: 768px) {
            .block-container {
                padding-left: 0.5rem;
                padding-right: 0.5rem;
            }
            table {
                font-size: 0.85rem;   /* smaller font for narrow screens */
            }
        }

        /* Scrollable tables */
        .table-container {
            overflow-x: auto;
        }

/* Tooltip & highlight stay the same */
        table {
            width: 100%;
        }
        th, td {
            padding: 0.3rem 0.6rem;
            text-align: center;
            white-space: nowrap;
        }
        h1, h2, h3, h4 {
            font-size: 1.1rem;
            margin-bottom: 0.5rem;
        }

        .table-group {
            display: flex;
            justify-content: flex-start;
            align-items: flex-start;
            gap: 1rem;
            overflow-x: auto;    /* Allow horizontal scroll if too wide */
            padding-bottom: 0.5rem;
        }
        .table-group > div {
            flex: 0 0 auto;      /* Prevent shrinking */
        }

        /* Tooltip styling */
        .tooltip {
            position: relative;
            cursor: help;
        }
        .tooltip .tooltiptext {
            visibility: hidden;
            width: max-content;
            max-width: 250px;
            background-color: #333;
            color: #fff;
            text-align: left;
            border-radius: 5px;
            padding: 5px;
            position: absolute;
            z-index: 1;
            bottom: 125%;
            left: 50%;
            transform: translateX(-50%);
            opacity: 0;
            transition: opacity 0.3s;
            white-space: normal;        /* allow line wrapping */
            word-wrap: break-word;      /* support long words */
        }
        .tooltip:hover .tooltiptext {
            visibility: visible;
            opacity: 1;
        }
        /* Highlight the td cell when hovering the tooltip */
        td:has(.tooltip:hover) {
            background-color: #f5f5a0;
            transition: background-color 0.2s ease-in-out;
        }
        
        .note-gold { color: #ffcc00; font-weight: bold; }
        .note-blue { color: #66ccff; font-weight: bold; } 
    </style>
""", unsafe_allow_html=True)

# Tooltip helper
def with_tooltip(word, note):
    return f'<span class="tooltip">{word}<span class="tooltiptext">{note}</span></span>'

# Custom table renderer (HTML not escaped to allow tooltips)
def show_table(title, data):
    df = pd.DataFrame(data, columns=["Person", "Singular", "Plural"])
    st.markdown(f"### {title}", unsafe_allow_html=True)
    st.markdown(df.to_html(escape=False, index=False), unsafe_allow_html=True)

# Show two tables side by side
def show_two(title1, data1, title2, data2):
    col1, col2 = st.columns(2)
    with col1:
        show_table(title1, data1)
    with col2:
        show_table(title2, data2)

# Show three tables side by side
def show_three(title1, data1, title2, data2, title3, data3):
    col1, col2, col3 = st.columns(3)
    with col1:
        show_table(title1, data1)
    with col2:
        show_table(title2, data2)
    with col3:
        show_table(title3, data3)


# ==============================
# Imperative Mood with Tooltips
# ==============================

# Present Imperative
present_active = [
    ["2nd", with_tooltip("λῦε", "Pres. Act. Imp. 2nd sg: Loose!"), with_tooltip("λύετε", "Pres. Act. Imp. 2nd pl: Loose! (plural)<br><span class='note-gold'>Also 2nd Pres.Act.Ind. 2nd pl</span>")],
    ["3rd", with_tooltip("λυέτω", "Pres. Act. Imp. 3rd sg: Let him/her loose!"), with_tooltip("λυέτωσαν", "Pres. Act. Imp. 3rd pl: Let them loose!")]
]
present_middle_passive = [
    ["2nd", with_tooltip("λύου", "Pres. Mid./Pass. Imp. 2nd sg: Loose for yourself! / Be loosed!"), with_tooltip("λύεσθε", "Pres. Mid./Pass. Imp. 2nd pl: Loose for yourselves! / Be loosed!")],
    ["3rd", with_tooltip("λυέσθω", "Pres. Mid./Pass. Imp. 3rd sg: Let him/her be loosed!"), with_tooltip("λυέσθωσαν", "Pres. Mid./Pass. Imp. 3rd pl: Let them be loosed!")]
]
show_two("<span class='note-blue'>Pres. Act. Imp.</span>", present_active, "<span class='note-blue'>Pres. Mid./Pass. Imp.</span>", present_middle_passive)


# Aorist Imperative
aorist_active = [
    ["2nd", with_tooltip("λῦσον", "1st Aor.Act.Imp. 2nd sg: Loose! (point action)"), with_tooltip("λύσατε", "1st Aor.Act.Imp. 2nd pl: Loose! (plural, point action)")],
    ["3rd", with_tooltip("λυσάτω", "1st Aor.Act.Imp. 3rd sg: Let him/her loose!"), with_tooltip("λυσάτωσαν", "1st Aor.Act.Imp. 3rd pl: Let them loose!")]
]
aorist_middle = [
    ["2nd", with_tooltip("λῦσαι", "1st Aor.Mid.Imp. 2nd sg: Loose for yourself!<br><span class='note-gold'>Also Aor.Act.Inf.</span>"), with_tooltip("λύσασθε", "1st Aor.Mid.Imp. 2nd pl: Loose for yourselves!")],
    ["3rd", with_tooltip("λυσάσθω", "1st Aor.Mid.Imp. 3rd sg: Let him/her loose for self!"), with_tooltip("λυσάσθωσαν", "1st Aor.Mid.Imp. 3rd pl: Let them loose for themselves!")]
]
aorist_passive = [
    ["2nd", with_tooltip("λύθητι", "1st Aor.Pass.Imp. 2nd sg: Be loosed!"), with_tooltip("λύθητε", "1st Aor.Pass.Imp. 2nd pl: Be loosed!")],
    ["3rd", with_tooltip("λυθήτω", "1st Aor.Pass.Imp. 3rd sg: Let him/her be loosed!"), with_tooltip("λυθήτωσαν", "1st Aor.Pass.Imp. 3rd pl: Let them be loosed!")]
]
show_three("<span class='note-blue'>Aor. Act. Imp.</span>", aorist_active, "<span class='note-blue'>Aor. Mid. Imp.</span>", aorist_middle, "<span class='note-blue'>Aor. Pass. Imp.</span>", aorist_passive)


# 2nd Aorist Imperative (for λάβω = I take)
second_aorist_active = [
    ["2nd", with_tooltip("λάβε", "2nd Aor.Act.Imp. 2nd sing: Take!"), with_tooltip("λάβετε", "2nd Aor.Act.Imp. 2nd pl: Take! (plural)")],
    ["3rd", with_tooltip("λαβέτω", "2nd Aor.Act.Imp. 3rd sing: Let him/her take!"), with_tooltip("λαβέτωσαν", "2nd Aor.Act.Imp. 3rd pl: Let them take!")]
]
second_aorist_middle = [
    ["2nd", with_tooltip("λαβοῦ", "2nd Aor.Mid.Imp. 2nd sg: Take for yourself!"), with_tooltip("λάβεσθε", "2nd Aor.Mid.Imp. 2nd pl: Take for yourselves!")],
    ["3rd", with_tooltip("λαβέσθω", "2nd Aor.Mid.Imp. 3rd sg: Let him/her take for self!"), with_tooltip("λαβέσθωσαν", "2nd Aor.Mid.Imp. 3rd pl: Let them take for themselves!")]
]
show_two("<span class='note-blue'>2nd Aor.Act.Imp.</span>", second_aorist_active, "<span class='note-blue'>2nd Aor.Mid./Pass.Imp.</span>", second_aorist_middle)
