# -*- coding: utf-8 -*-
"""indicative_mouseover.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cKdGKlxjW5Pm18RvUeH88HCTiamqNUP7
"""

import streamlit as st
import pandas as pd

st.title("Indicative of λύω")

# Inject custom CSS for layout + tooltips
st.markdown("""
    <style>
        .block-container {
            max-width: unset;
            padding-left: 15rem;
            padding-right: 15rem;
            padding-top: 2rem;
            padding-bottom: 1rem;
            overflow-x: auto;
        }

        /* Responsive adjustments for mobile */
        @media (max-width: 768px) {
            .block-container {
                padding-left: 0.5rem;
                padding-right: 0.5rem;
            }
            table {
                font-size: 0.85rem;   /* smaller font for narrow screens */
            }
        }

        /* Scrollable tables */
        .table-container {
            overflow-x: auto;
        }

/* Tooltip & highlight stay the same */
        table {
            width: 100%;
        }
        th, td {
            padding: 0.3rem 0.6rem;
            text-align: center;
            white-space: nowrap;
            position: relative; /* <-- anchor tooltip inside each table cell */
        }
        h1, h2, h3, h4 {
            font-size: 1.1rem;
            margin-bottom: 0.5rem;
        }

        }
        /* Tooltip styling */
        .tooltip {
            position: relative;
            cursor: help;
        }
        .tooltip .tooltiptext {
            visibility: hidden;
            width: max-content;
            max-width: 250px;
            background-color: #333;
            color: #fff;
            text-align: left;
            border-radius: 5px;
            padding: 6px 10px;
            position: absolute;
            z-index: 1;
            bottom: 115%;
            left: 50%;
            transform: translateX(-50%);
            margin-bottom: 2px; /* tiny gap so it "sticks" closer */
            opacity: 0;
            transition: opacity 0.3s;
            white-space: normal;        /* allow line wrapping */
            word-wrap: break-word;      /* support long words */
        }
        .tooltip:hover .tooltiptext {
            visibility: visible;
            opacity: 1;
        }
        /* Highlight the td cell when hovering the tooltip */
        td:has(.tooltip:hover) {
            background-color: #f5f5a0;
            transition: background-color 0.2s ease-in-out;
        }
        .note-gold { color: #ffcc00; font-weight: bold; }
        .note-blue { color: #66ccff; font-weight: bold; } 
    </style>
""", unsafe_allow_html=True)

# Tooltip helper
def with_tooltip(word, note):
    return f'<span class="tooltip">{word}<span class="tooltiptext">{note}</span></span>'

# Display helpers
def show_table(title, data):
    df = pd.DataFrame(data, columns=["Person", "Singular", "Plural"])
    st.markdown(f"### {title}", unsafe_allow_html=True)
    st.markdown(df.to_html(escape=False, index=False), unsafe_allow_html=True)

def show_two(title1, data1, title2, data2):
    col1, col2 = st.columns([1, 1])
    with col1:
        show_table(title1, data1)
    with col2:
        show_table(title2, data2)

def show_three(title1, data1, title2, data2, title3, data3):
    col1, col2, col3 = st.columns([1, 1, 1])
    with col1:
        show_table(title1, data1)
    with col2:
        show_table(title2, data2)
    with col3:
        show_table(title3, data3)


# ==============================
# Indicative Tables with Tooltips
# ==============================

# Present Indicative
present_active = [
    ["1st", with_tooltip("λύω", "Present Active 1st singular: I loose.<br><span class='note-gold'>Also Pres.Act.Subj. 1st sing.</span>"), with_tooltip("λύομεν", "Present Active 1st plural: we loose")],
    ["2nd", with_tooltip("λύεις", "Present Active 2nd singular: you loose"), with_tooltip("λύετε", "Pres.Act.Ind.2nd.plural: you (pl) loose.<br><span class='note-gold'>Also Pres.Act.Imp. 2nd pl</span>")],
    ["3rd", with_tooltip("λύει", "Present Active 3rd singular: he/she/it looses"), with_tooltip("λύουσι(ν)", "Present Active 3rd plural: they loose")]
]
present_mp = [
    ["1st", with_tooltip("λύομαι", "Present Middle/Passive 1st singular: I loose for myself/am loosed"), with_tooltip("λυόμεθα", "Present Middle/Passive 1st plural: we loose for ourselves/are loosed")],
    ["2nd", with_tooltip("λύῃ", "Present Middle/Passive 2nd singular: you loose for yourself/are loosed.<br><span class='note-gold'>Also Pres.Act.Subj. 3rd sing.</span><br><span class='note-gold'>Also Pres.Mid./Pass.Subj. 2nd sing.</span>"), with_tooltip("λύεσθε", "Present Middle/Passive 2nd plural: you (pl) are loosed")],
    ["3rd", with_tooltip("λύεται", "Present Middle/Passive 3rd singular: he/she/it is loosed"), with_tooltip("λύονται", "Present Middle/Passive 3rd plural: they are loosed")]
]
show_two("<span class='note-blue'>Pres. Act. Ind.</span>", present_active, "<span class='note-blue'>Pres. Mid./Pass. Ind.</span>", present_mp)


# Imperfect Indicative
imperfect_active = [
    ["1st", with_tooltip("ἔλυον", "Imperfect Active 1st singular: I was loosing.<br><span class='note-gold'>Also Imp.Act.Ind. 3rd pl</span>"), with_tooltip("ἐλύομεν", "Imperfect Active 1st plural: we were loosing")],
    ["2nd", with_tooltip("ἔλυες", "Imperfect Active 2nd singular: you were loosing"), with_tooltip("ἐλύετε", "Imperfect Active 2nd plural: you (pl) were loosing")],
    ["3rd", with_tooltip("ἔλυε(ν)", "Imperfect Active 3rd singular: he/she/it was loosing"), with_tooltip("ἔλυον", "Imperfect Active 3rd plural: they were loosing.<br><span class='note-gold'>Also Imp.Act.Ind. 1st sing.</span>")]
]
imperfect_mp = [
    ["1st", with_tooltip("ἐλυόμην", "Imperfect Mid./Pass. 1st singular: I was being loosed"), with_tooltip("ἐλυόμεθα", "Imperfect Mid./Pass. 1st plural: we were being loosed")],
    ["2nd", with_tooltip("ἐλύου", "Imperfect Mid./Pass. 2nd singular: you were being loosed"), with_tooltip("ἐλύεσθε", "Imperfect Mid./Pass. 2nd plural: you (pl) were being loosed")],
    ["3rd", with_tooltip("ἐλύετο", "Imperfect Mid./Pass. 3rd singular: he/she/it was being loosed"), with_tooltip("ἐλύοντο", "Imperfect Mid./Pass. 3rd plural: they were being loosed")]
]
show_two("<span class='note-blue'>Imp. Act. Ind.</span>", imperfect_active, "<span class='note-blue'>Imp. Mid./Pass. Ind.</span>", imperfect_mp)


# Future Indicative
future_active = [
    ["1st", with_tooltip("λύσω", "Future Active 1st singular: I will loose<br><span class='note-gold'>Also Aor.Act.Subj. 1st sing.</span>"), with_tooltip("λύσομεν", "Future Active 1st plural: we will loose")],
    ["2nd", with_tooltip("λύσεις", "Future Active 2nd singular: you will loose"), with_tooltip("λύσετε", "Future Active 2nd plural: you (pl) will loose")],
    ["3rd", with_tooltip("λύσει", "Future Active 3rd singular: he/she/it will loose"), with_tooltip("λύσουσι(ν)", "Future Active 3rd plural: they will loose")]
]
future_middle = [
    ["1st", with_tooltip("λύσομαι", "Future Middle 1st singular: I will loose for myself"), with_tooltip("λυσόμεθα", "Future Middle 1st plural: we will loose for ourselves")],
    ["2nd", with_tooltip("λύσῃ", "Future Middle 2nd singular: you will loose for yourself. <br><span class='note-gold'>Also Aor.Act.Subj. 3rd sing.</span>"), with_tooltip("λύσεσθε", "Future Middle 2nd plural: you (pl) will loose for yourselves")],
    ["3rd", with_tooltip("λύσεται", "Future Middle 3rd singular: he/she/it will loose for itself"), with_tooltip("λύσονται", "Future Middle 3rd plural: they will loose for themselves")]
]
future_passive = [
    ["1st", with_tooltip("λυθήσομαι", "Future Passive 1st singular: I will be loosed"), with_tooltip("λυθησόμεθα", "Future Passive 1st plural: we will be loosed")],
    ["2nd", with_tooltip("λυθήσῃ", "Future Passive 2nd singular: you will be loosed"), with_tooltip("λυθήσεσθε", "Future Passive 2nd plural: you (pl) will be loosed")],
    ["3rd", with_tooltip("λυθήσεται", "Future Passive 3rd singular: he/she/it will be loosed"), with_tooltip("λυθήσονται", "Future Passive 3rd plural: they will be loosed")]
]
show_three("<span class='note-blue'>Fut. Act. Ind.</span>", future_active, "<span class='note-blue'>Fut. Mid. Ind.</span>", future_middle, "<span class='note-blue'>Fut. Pass. Ind.</span>", future_passive)


# Aorist (1st) Indicative
aorist1_active = [
    ["1st", with_tooltip("ἔλυσα", "1st Aorist Active 1st singular: I loosed"), with_tooltip("ἐλύσαμεν", "1st Aorist Active 1st plural: we loosed")],
    ["2nd", with_tooltip("ἔλυσας", "1st Aorist Active 2nd singular: you loosed"), with_tooltip("ἐλύσατε", "1st Aorist Active 2nd plural: you (pl) loosed")],
    ["3rd", with_tooltip("ἔλυσε(ν)", "1st Aorist Active 3rd singular: he/she/it loosed"), with_tooltip("ἔλυσαν", "1st Aorist Active 3rd plural: they loosed")]
]
aorist1_middle = [
    ["1st", with_tooltip("ἐλυσάμην", "1st Aorist Middle 1st singular: I loosed for myself"), with_tooltip("ἐλυσάμεθα", "1st Aorist Middle 1st plural: we loosed for ourselves")],
    ["2nd", with_tooltip("ἐλύσω", "1st Aorist Middle 2nd singular: you loosed for yourself"), with_tooltip("ἐλύσασθε", "1st Aorist Middle 2nd plural: you (pl) loosed for yourselves")],
    ["3rd", with_tooltip("ἐλύσατο", "1st Aorist Middle 3rd singular: he/she/it loosed for self"), with_tooltip("ἐλύσαντο", "1st Aorist Middle 3rd plural: they loosed for themselves")]
]
aorist1_passive = [
    ["1st", with_tooltip("ἐλύθην", "1st Aorist Passive 1st singular: I was loosed"), with_tooltip("ἐλύθημεν", "1st Aorist Passive 1st plural: we were loosed")],
    ["2nd", with_tooltip("ἐλύθης", "1st Aorist Passive 2nd singular: you were loosed"), with_tooltip("ἐλύθητε", "1st Aorist Passive 2nd plural: you (pl) were loosed")],
    ["3rd", with_tooltip("ἐλύθη", "1st Aorist Passive 3rd singular: he/she/it was loosed"), with_tooltip("ἐλύθησαν", "1st Aorist Passive 3rd plural: they were loosed")]
]
show_three("<span class='note-blue'>Aor. Act. Ind.</span>", aorist1_active, "<span class='note-blue'>Aor. Mid. Ind.</span>", aorist1_middle, "<span class='note-blue'>Aor. Pass. Ind.</span>", aorist1_passive)


# Aorist (2nd) Indicative (different stems!)
aorist2_active = [
    ["1st", with_tooltip("ἔλαβον", "2nd Aorist Active 1st singular: I took"), with_tooltip("ἐλάβομεν", "2nd Aorist Active 1st plural: we took")],
    ["2nd", with_tooltip("ἔλαβες", "2nd Aorist Active 2nd singular: you took"), with_tooltip("ἐλάβετε", "2nd Aorist Active 2nd plural: you (pl) took")],
    ["3rd", with_tooltip("ἔλαβε(ν)", "2nd Aorist Active 3rd singular: he/she/it took"), with_tooltip("ἔλαβον", "2nd Aorist Active 3rd plural: they took")]
]
aorist2_middle = [
    ["1st", with_tooltip("ἐλαβόμην", "2nd Aorist Middle 1st singular: I took (for myself)"), with_tooltip("ἐλαβόμεθα", "2nd Aorist Middle 1st plural: we took for ourselves")],
    ["2nd", with_tooltip("ἐλάβου", "2nd Aorist Middle 2nd singular: you took for yourself"), with_tooltip("ἐλάβεσθε", "2nd Aorist Middle 2nd plural: you (pl) took for yourselves")],
    ["3rd", with_tooltip("ἐλάβετο", "2nd Aorist Middle 3rd singular: he/she took for self"), with_tooltip("ἐλάβοντο", "2nd Aorist Middle 3rd plural: they took for themselves")]
]
aorist2_passive = [
    ["1st", with_tooltip("ἐγράφην", "2nd Aorist Passive 1st singular: I was written"), with_tooltip("ἐγράφημεν", "2nd Aorist Passive 1st plural: we were written")],
    ["2nd", with_tooltip("ἐγράφης", "2nd Aorist Passive 2nd singular: you were written"), with_tooltip("ἐγράφητε", "2nd Aorist Passive 2nd plural: you (pl) were written")],
    ["3rd", with_tooltip("ἐγράφη", "2nd Aorist Passive 3rd singular: he/she/it was written"), with_tooltip("ἐγράφησαν", "2nd Aorist Passive 3rd plural: they were written")]
]
show_three("<span class='note-blue'>2nd Aor. Act. Ind.</span>", aorist2_active, "<span class='note-blue'>2nd Aor. Mid. Ind.</span>", aorist2_middle, "<span class='note-blue'>2nd Aor. Pass. Ind.</span>", aorist2_passive)


# Perfect Indicative
perfect_active = [
    ["1st", with_tooltip("λέλυκα", "Perfect Active 1st singular: I have loosed"), with_tooltip("λελύκαμεν", "Perfect Active 1st plural: we have loosed")],
    ["2nd", with_tooltip("λέλυκας", "Perfect Active 2nd singular: you have loosed"), with_tooltip("λελύκατε", "Perfect Active 2nd plural: you (pl) have loosed")],
    ["3rd", with_tooltip("λέλυκε(ν)", "Perfect Active 3rd singular: he/she/it has loosed"), with_tooltip("λελύκασι(ν)", "Perfect Active 3rd plural: they have loosed")]
]
perfect_middle = [
    ["1st", with_tooltip("λέλυμαι", "Perfect Mid./Pass. 1st singular: I have loosed for myself / have been loosed"), with_tooltip("λελύμεθα", "Perfect Mid./Pass. 1st plural: we have loosed for ourselves / have been loosed")],
    ["2nd", with_tooltip("λέλυσαι", "Perfect Mid./Pass. 2nd singular: you have loosed for yourself / have been loosed"), with_tooltip("λέλυσθε", "Perfect Mid./Pass. 2nd plural: you (pl) have been loosed")],
    ["3rd", with_tooltip("λέλυται", "Perfect Mid./Pass. 3rd singular: he/she/it has been loosed"), with_tooltip("λέλυνται", "Perfect Mid./Pass. 3rd plural: they have been loosed")]
]
# Passive is the same as middle
perfect_passive = perfect_middle
show_three("<span class='note-blue'>Perf. Act. Ind.</span>", perfect_active, "<span class='note-blue'>Perf. Mid. Ind.</span>", perfect_middle, "<span class='note-blue'>Perf. Pass. Ind.</span>", perfect_passive)


# Pluperfect Indicative
pluperfect_active = [
    ["1st", with_tooltip("ἐλελύκη", "Pluperfect Active 1st singular: I had loosed"), with_tooltip("ἐλελύκεμεν", "Pluperfect Active 1st plural: we had loosed")],
    ["2nd", with_tooltip("ἐλελύκης", "Pluperfect Active 2nd singular: you had loosed"), with_tooltip("ἐλελύκετε", "Pluperfect Active 2nd plural: you (pl) had loosed")],
    ["3rd", with_tooltip("ἐλελύκει", "Pluperfect Active 3rd singular: he/she/it had loosed"), with_tooltip("ἐλελύκεσαν", "Pluperfect Active 3rd plural: they had loosed")]
]
pluperfect_middle = [
    ["1st", with_tooltip("ἐλελύμην", "Pluperfect Mid./Pass. 1st singular: I had been loosed"), with_tooltip("ἐλελύμεθα", "Pluperfect Mid./Pass. 1st plural: we had been loosed")],
    ["2nd", with_tooltip("ἐλέλυσο", "Pluperfect Mid./Pass. 2nd singular: you had been loosed"), with_tooltip("ἐλέλυσθε", "Pluperfect Mid./Pass. 2nd plural: you (pl) had been loosed")],
    ["3rd", with_tooltip("ἐλέλυτο", "Pluperfect Mid./Pass. 3rd singular: he/she/it had been loosed"), with_tooltip("ἐλέλυντο", "Pluperfect Mid./Pass. 3rd plural: they had been loosed")]
]
# Passive is same as middle
pluperfect_passive = pluperfect_middle
show_three("<span class='note-blue'>Plupf. Act. Ind.</span>", pluperfect_active, "<span class='note-blue'>Plupf. Mid. Ind.</span>", pluperfect_middle, "<span class='note-blue'>Plupf. Pass. Ind.</span>", pluperfect_passive)
