# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sBAgZzJvlSsnGBpkqdBt9bLuOSXqEl6R
"""

import streamlit as st
import pandas as pd

st.title("Infinitive Forms of λύω")

# = CSS styling with tooltip support =
st.markdown("""
    <style>
        .block-container {
            max-width: unset;
            padding-left: 15rem;
            padding-right: 15rem;
            padding-top: 2rem;
            padding-bottom: 1rem;
            overflow-x: auto;
        }

        @media (max-width: 768px) {
            .block-container {
                padding-left: 0.5rem;
                padding-right: 0.5rem;
            }
            table {
                font-size: 0.85rem;
            }
        }

        .table-container {
            overflow-x: auto;
        }

        table {
            width: 100%;
        }
        th, td {
            padding: 0.3rem 0.6rem;
            text-align: center;
            white-space: nowrap;
        }
        h1, h2, h3, h4 {
            font-size: 1.1rem;
            margin-bottom: 0.5rem;
        }

        .tooltip {
            position: relative;
            cursor: help;
        }
        .tooltip .tooltiptext {
            visibility: hidden;
            width: max-content;
            max-width: 250px;
            background-color: #333;
            color: #fff;
            text-align: left;
            border-radius: 5px;
            padding: 5px;
            position: absolute;
            z-index: 1;
            bottom: 125%;
            left: 50%;
            transform: translateX(-50%);
            opacity: 0;
            transition: opacity 0.3s;
            white-space: normal;
            word-wrap: break-word;
        }
        .tooltip:hover .tooltiptext {
            visibility: visible;
            opacity: 1;
        }
        td:has(.tooltip:hover) {
            background-color: #f5f5a0;
            transition: background-color 0.2s ease-in-out;
        }

        .note-gold { color: #ffcc00; font-weight: bold; }
        .note-blue { color: #66ccff; font-weight: bold; }
    </style>
""", unsafe_allow_html=True)

# Tooltip helper
def with_tooltip(word, note):
    return f'<span class="tooltip">{word}<span class="tooltiptext">{note}</span></span>'

# Custom table renderer
def show_table(title, data):
    df = pd.DataFrame(data, columns=["Voice", "Form"])
    st.markdown(f"### {title}", unsafe_allow_html=True)
    st.markdown(df.to_html(escape=False, index=False), unsafe_allow_html=True)

# ==============================
# Infinitive Mood with Tooltips
# ==============================

# Present Infinitive
present_infinitives = [
    ["Active", with_tooltip("λύειν", "Pres. Act. Inf.: to be loosing")],
    ["Middle/Passive", with_tooltip("λύεσθαι", "Pres. Mid./Pass. Inf.: to be loosing for oneself / to be loosed")]
]

# First Aorist Infinitive
aorist_infinitives = [
    ["Active", with_tooltip("λῦσαι", "1st Aor. Act. Inf.: to loose (point action)<br><span class='note-gold'>Also Aor.Mid.Imp. 2nd sg</span>")],
    ["Middle", with_tooltip("λύσασθαι", "1st Aor. Mid. Inf.: to loose for oneself")],
    ["Passive", with_tooltip("λυθῆναι", "1st Aor. Pass. Inf.: to be loosed")]
]

# Second Aorist Infinitive (for λαμβάνω)
second_aorist_infinitives = [
    ["Active", with_tooltip("λαβεῖν", "2nd Aor. Act. Inf.: to take")],
    ["Middle", with_tooltip("λαβέσθαι", "2nd Aor. Mid. Inf.: to take for oneself")],
    ["Passive", with_tooltip("ληφθῆναι", "2nd Aor. Pass. Inf.: to be taken")]
]

# Display tables
show_table("<span class='note-blue'>Present Infinitive</span>", present_infinitives)
show_table("<span class='note-blue'>1st Aorist Infinitive</span>", aorist_infinitives)
show_table("<span class='note-blue'>2nd Aorist Infinitive (λαμβάνω)</span>", second_aorist_infinitives)
