# -*- coding: utf-8 -*-
"""subjunctive_mouseover.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10hVWTDKSG-z93Iu09Nl5ACFvaGDZtUqY
"""

import streamlit as st
import pandas as pd

st.title("Subjunctive of λύω")

# CSS for tooltips and highlighting
st.markdown("""
    <style>
        .block-container {
            max-width: unset;
            padding-left: 15rem;
            padding-right: 15rem;
            padding-top: 2rem;
            padding-bottom: 1rem;
        }
        table {
            width: 100%;
        }
        th, td {
            padding: 0.3rem 0.6rem;
            text-align: center;
            white-space: nowrap;
        }
        h1, h2, h3, h4 {
            font-size: 1.1rem;
            margin-bottom: 0.5rem;
        }
        /* Tooltip styling */
        .tooltip {
            position: relative;
            cursor: help;
        }
        .tooltip .tooltiptext {
            visibility: hidden;
            min-width: 300px;
            max-width: 600px;
            background-color: #333;
            color: #fff;
            text-align: left;
            border-radius: 6px;
            padding: 8px 12px;
            position: absolute;
            z-index: 1;
            bottom: 125%;
            left: 50%;
            transform: translateX(-50%);
            opacity: 0;
            transition: opacity 0.3s;
            white-space: normal;
            word-wrap: break-word;
        }
        .tooltip:hover .tooltiptext {
            visibility: visible;
            opacity: 1;
        }
        /* Highlight TD when tooltip active */
        td:has(.tooltip:hover) {
            background-color: #f5f5a0;
            transition: background-color 0.2s ease-in-out;
        .note-gold { color: #ffcc00; font-weight: bold; }
        .note-blue { color: #66ccff; font-weight: bold; } 
        }
    </style>
""", unsafe_allow_html=True)

# Tooltip builder
def with_tooltip(word, note_html):
    return f'<span class="tooltip">{word}<span class="tooltiptext">{note_html}</span></span>'

# Custom table display
def show_table(title, data):
    df = pd.DataFrame(data, columns=["Person", "Singular", "Plural"])
    st.markdown(f"### {title}", unsafe_allow_html=True)
    st.markdown(df.to_html(escape=False, index=False), unsafe_allow_html=True)

def show_two(title1, data1, title2, data2):
    col1, col2 = st.columns(2)
    with col1:
        show_table(title1, data1)
    with col2:
        show_table(title2, data2)

def show_three(title1, data1, title2, data2, title3, data3):
    col1, col2, col3 = st.columns(3)
    with col1:
        show_table(title1, data1)
    with col2:
        show_table(title2, data2)
    with col3:
        show_table(title3, data3)

# =============================
# Subjunctive Forms with Tooltips
# =============================

# Present Subjunctive
present_active = [
    ["1st", with_tooltip("λύω", "Pres. Act. Subj. 1st Sg — that I may loose.<br><span class='note-gold'>Also Pres.Act.Ind. 1st sing.</span>"), with_tooltip("λύωμεν", "Pres. Act. Subj. 1st Pl — that we may loose")],
    ["2nd", with_tooltip("λύῃς", "Pres. Act. Subj. 2nd Sg — that you may loose"), with_tooltip("λύητε", "Pres. Act. Subj. 2nd Pl — that you (pl) may loose")],
    ["3rd", with_tooltip("λύῃ", "Pres. Act. Subj. 3rd Sg — that he/she/it may loose"), with_tooltip("λύωσι(ν)", "Pres. Act. Subj. 3rd Pl — that they may loose")]
]
present_mp = [
    ["1st", with_tooltip("λύωμαι", "Pres. Mid./Pass. Subj. 1st Sg — that I may loose for myself / may be loosed"), with_tooltip("λυώμεθα", "Pres. Mid./Pass. Subj. 1st Pl — that we may loose for ourselves / may be loosed")],
    ["2nd", with_tooltip("λύῃ", "Pres. Mid./Pass. Subj. 2nd Sg — that you may loose for yourself / may be loosed"), with_tooltip("λύησθε", "Pres. Mid./Pass. Subj. 2nd Pl — that you (pl) may be loosed")],
    ["3rd", with_tooltip("λύηται", "Pres. Mid./Pass. Subj. 3rd Sg — that he/she/it may be loosed"), with_tooltip("λύωνται", "Pres. Mid./Pass. Subj. 3rd Pl — that they may be loosed")]
]
show_two("<span class='note-blue'>Pres. Act. Subj.</span>", present_active, "Pres. Mid./Pass. Subj.", present_mp)

# Aorist Subjunctive
aorist_active = [
    ["1st", with_tooltip("λύσω", "1st Aor. Act. Subj. 1st Sg — that I may loose (point-in-time)"), with_tooltip("λύσωμεν", "1st Aor. Act. Subj. 1st Pl — that we may loose")],
    ["2nd", with_tooltip("λύσῃς", "1st Aor. Act. Subj. 2nd Sg — that you may loose"), with_tooltip("λύσητε", "1st Aor. Act. Subj. 2nd Pl — that you (pl) may loose")],
    ["3rd", with_tooltip("λύσῃ", "1st Aor. Act. Subj. 3rd Sg — that he/she/it may loose"), with_tooltip("λύσωσι(ν)", "1st Aor. Act. Subj. 3rd Pl — that they may loose")]
]
aorist_middle = [
    ["1st", with_tooltip("λύσωμαι", "1st Aor. Mid. Subj. 1st Sg — that I may loose for myself"), with_tooltip("λυσώμεθα", "1st Aor. Mid. Subj. 1st Pl — that we may loose for ourselves")],
    ["2nd", with_tooltip("λύσῃ", "1st Aor. Mid. Subj. 2nd Sg — that you may loose for yourself"), with_tooltip("λύσησθε", "1st Aor. Mid. Subj. 2nd Pl — that you (pl) may loose for yourselves")],
    ["3rd", with_tooltip("λύσηται", "1st Aor. Mid. Subj. 3rd Sg — that he/she may loose for self"), with_tooltip("λύσωνται", "1st Aor. Mid. Subj. 3rd Pl — that they may loose for themselves")]
]
aorist_passive = [
    ["1st", with_tooltip("λυθῶ", "1st Aor. Pass. Subj. 1st Sg — that I may be loosed"), with_tooltip("λυθῶμεν", "1st Aor. Pass. Subj. 1st Pl — that we may be loosed")],
    ["2nd", with_tooltip("λυθῇς", "1st Aor. Pass. Subj. 2nd Sg — that you may be loosed"), with_tooltip("λυθῆτε", "1st Aor. Pass. Subj. 2nd Pl — that you (pl) may be loosed")],
    ["3rd", with_tooltip("λυθῇ", "1st Aor. Pass. Subj. 3rd Sg — that he/she/it may be loosed"), with_tooltip("λυθῶσι(ν)", "1st Aor. Pass. Subj. 3rd Pl — that they may be loosed")]
]
show_three("Aor. Act. Subj.", aorist_active, "Aor. Mid. Subj.", aorist_middle, "Aor. Pass. Subj.", aorist_passive)

# Perfect Subjunctive (only Active generally attested)
perfect_active = [
    ["1st", with_tooltip("λελύκω", "Perf. Act. Subj. 1st Sg — that I may have loosed"), with_tooltip("λελύκωμεν", "Perf. Act. Subj. 1st Pl — that we may have loosed")],
    ["2nd", with_tooltip("λελύκῃς", "Perf. Act. Subj. 2nd Sg — that you may have loosed"), with_tooltip("λελύκητε", "Perf. Act. Subj. 2nd Pl — that you (pl) may have loosed")],
    ["3rd", with_tooltip("λελύκῃ", "Perf. Act. Subj. 3rd Sg — that he/she/it may have loosed"), with_tooltip("λελύκωσι(ν)", "Perf. Act. Subj. 3rd Pl — that they may have loosed")]
]
st.subheader("Perf. Act. Subj.")
col1, col2, col3 = st.columns([1, 1, 1])
with col1:
    df_perfect_active = pd.DataFrame(perfect_active, columns=["Person", "Singular", "Plural"])
    st.markdown(df_perfect_active.to_html(escape=False, index=False), unsafe_allow_html=True)
# col2 and col3 remain empty, so the table only takes up 1/3 width

